# -*- coding: utf-8 -*-
"""moduloaux

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1slw6OhN48OJo6mEp7af9SLHdqj7T1lzw
"""

# presión litosférica                      m    *   Kg   *  m  =  Kg    (Pa)
# con función interna                     s^2       m^3     1    s^2*m
h= None
g=float(9.8) #m/s^2
p=float(2691) #Kg/m^3

fmt='%3.3f'
#------------------------------------
while h!=0.0 and h!=-0.0:
  h=float(input('Ingrese la profundidad (en Km negativos) a la cual desea evaluar la presión litostática de la Tierra, 0 para finalizar: '))
  def presion_litostatica_mod(g,p,h):
    #Hacer presión litostática + presión hidrostática
      P = (-1*g*p*(h*1000)) #N/m^2
      return P
  print('La presión litostátia a una profundidad de',h,'Km es de',fmt%((presion_litostatica_mod(g,p,h))/1000000),'MPa (Mega-Pascales)')
  #------------------------------------
print('Fin del programa')
print('Este fue el auxiliar')

